const inputBox = document.getElementById('answer-input-box');
const submitted = document.getElementById('answer-submitted');
const question = document.getElementById('question');
const info = document.getElementById('answer-info');
var correctAnswer = null;
var qnum = -1;
var maxQuestions = 100;
var played = 0;
var score = 0;

// Hard coded data. Very ugly, but at least it works
var data = ["Grande Arche de La Defense (-> Chateau de Vincennes);Esplanade de La Defense",
"Esplanade de La Defense (-> Chateau de Vincennes);Pont de Neuilly",
"Pont de Neuilly (-> Chateau de Vincennes);Les Sablons",
"Les Sablons (-> Chateau de Vincennes);Porte Maillot",
"Porte Maillot (-> Chateau de Vincennes);Argentine",
"Argentine (-> Chateau de Vincennes);Charles de Gaulle - Etoile",
"Charles de Gaulle - Etoile (-> Chateau de Vincennes);George V",
"George V (-> Chateau de Vincennes);Franklin-D. Roosevelt",
"Franklin-D. Roosevelt (-> Chateau de Vincennes);Champs Elysees - Clemenceau",
"Champs Elysees - Clemenceau (-> Chateau de Vincennes);Concorde",
"Concorde (-> Chateau de Vincennes);Tuileries",
"Tuileries (-> Chateau de Vincennes);Palais Royal - Musee du Louvre",
"Palais Royal - Musee du Louvre (-> Chateau de Vincennes);Louvre - Rivoli",
"Louvre - Rivoli (-> Chateau de Vincennes);Chatelet",
"Chatelet (-> Chateau de Vincennes);Hotel de Ville",
"Hotel de Ville (-> Chateau de Vincennes);Saint-Paul",
"Saint-Paul (-> Chateau de Vincennes);Bastille",
"Bastille (-> Chateau de Vincennes);Gare de Lyon",
"Gare de Lyon (-> Chateau de Vincennes);Reuilly - Diderot",
"Reuilly - Diderot (-> Chateau de Vincennes);Nation",
"Nation (-> Chateau de Vincennes);Porte de Vincennes",
"Porte de Vincennes (-> Chateau de Vincennes);Saint-Mande - Tourelle",
"Saint-Mande - Tourelle (-> Chateau de Vincennes);Berault",
"Berault (-> Chateau de Vincennes);Chateau de Vincennes",
"Chateau de Vincennes (-> La Defense);Berault",
"Berault (-> La Defense);Saint-Mande - Tourelle",
"Saint-Mande - Tourelle (-> La Defense);Porte de Vincennes",
"Porte de Vincennes (-> La Defense);Nation",
"Nation (-> La Defense);Reuilly - Diderot",
"Reuilly - Diderot (-> La Defense);Gare de Lyon",
"Gare de Lyon (-> La Defense);Bastille",
"Bastille (-> La Defense);Saint-Paul",
"Saint-Paul (-> La Defense);Hotel de Ville",
"Hotel de Ville (-> La Defense);Chatelet",
"Chatelet (-> La Defense);Louvre - Rivoli",
"Louvre - Rivoli (-> La Defense);Palais Royal - Musee du Louvre",
"Palais Royal - Musee du Louvre (-> La Defense);Tuileries",
"Tuileries (-> La Defense);Concorde",
"Concorde (-> La Defense);Champs Elysees - Clemenceau",
"Champs Elysees - Clemenceau (-> La Defense);Franklin-D. Roosevelt",
"Franklin-D. Roosevelt (-> La Defense);George V",
"George V (-> La Defense);Charles de Gaulle - Etoile",
"Charles de Gaulle - Etoile (-> La Defense);Argentine",
"Argentine (-> La Defense);Porte Maillot",
"Porte Maillot (-> La Defense);Les Sablons",
"Les Sablons (-> La Defense);Pont de Neuilly",
"Pont de Neuilly (-> La Defense);Esplanade de La Defense",
"Esplanade de La Defense (-> La Defense);Grande Arche de La Defense",
"Porte Dauphine (-> Nation);Victor Hugo",
"Victor Hugo (-> Nation);Charles de Gaulle - Etoile",
"Charles de Gaulle - Etoile (-> Nation);Ternes",
"Ternes (-> Nation);Courcelles",
"Courcelles (-> Nation);Monceau",
"Monceau (-> Nation);Villiers",
"Villiers (-> Nation);Rome",
"Rome (-> Nation);Place de Clichy",
"Place de Clichy (-> Nation);Blanche",
"Blanche (-> Nation);Pigalle",
"Pigalle (-> Nation);Anvers",
"Anvers (-> Nation);Barbes - Rochechouart",
"Barbes - Rochechouart (-> Nation);La Chapelle",
"La Chapelle (-> Nation);Stalingrad",
"Stalingrad (-> Nation);Jaures",
"Jaures (-> Nation);Colonel Fabien",
"Colonel Fabien (-> Nation);Belleville",
"Belleville (-> Nation);Couronnes",
"Couronnes (-> Nation);Menilmontant",
"Menilmontant (-> Nation);Pere Lachaise",
"Pere Lachaise (-> Nation);Philippe Auguste",
"Philippe Auguste (-> Nation);Alexandre Dumas",
"Alexandre Dumas (-> Nation);Avron",
"Avron (-> Nation);Nation",
"Nation (-> Porte Dauphine);Avron",
"Avron (-> Porte Dauphine);Alexandre Dumas",
"Alexandre Dumas (-> Porte Dauphine);Philippe Auguste",
"Philippe Auguste (-> Porte Dauphine);Pere Lachaise",
"Pere Lachaise (-> Porte Dauphine);Menilmontant",
"Menilmontant (-> Porte Dauphine);Couronnes",
"Couronnes (-> Porte Dauphine);Belleville",
"Belleville (-> Porte Dauphine);Colonel Fabien",
"Colonel Fabien (-> Porte Dauphine);Jaures",
"Jaures (-> Porte Dauphine);Stalingrad",
"Stalingrad (-> Porte Dauphine);La Chapelle",
"La Chapelle (-> Porte Dauphine);Barbes - Rochechouart",
"Barbes - Rochechouart (-> Porte Dauphine);Anvers",
"Anvers (-> Porte Dauphine);Pigalle",
"Pigalle (-> Porte Dauphine);Blanche",
"Blanche (-> Porte Dauphine);Place de Clichy",
"Place de Clichy (-> Porte Dauphine);Rome",
"Rome (-> Porte Dauphine);Villiers",
"Villiers (-> Porte Dauphine);Monceau",
"Monceau (-> Porte Dauphine);Courcelles",
"Courcelles (-> Porte Dauphine);Ternes",
"Ternes (-> Porte Dauphine);Charles de Gaulle - Etoile",
"Charles de Gaulle - Etoile (-> Porte Dauphine);Victor Hugo",
"Victor Hugo (-> Porte Dauphine);Porte Dauphine",
"Pont de Levallois - Becon (-> Gallieni);Anatole France",
"Anatole France (-> Gallieni);Louise Michel",
"Louise Michel (-> Gallieni);Porte de Champerret",
"Porte de Champerret (-> Gallieni);Pereire",
"Pereire (-> Gallieni);Wagram",
"Wagram (-> Gallieni);Malesherbes",
"Malesherbes (-> Gallieni);Villiers",
"Villiers (-> Gallieni);Europe",
"Europe (-> Gallieni);Saint-Lazare",
"Saint-Lazare (-> Gallieni);Havre - Caumartin",
"Havre - Caumartin (-> Gallieni);Opera",
"Opera (-> Gallieni);Quatre Septembre",
"Quatre Septembre (-> Gallieni);Bourse",
"Bourse (-> Gallieni);Sentier",
"Sentier (-> Gallieni);Reaumur - Sebastopol",
"Reaumur - Sebastopol (-> Gallieni);Arts et Metiers",
"Arts et Metiers (-> Gallieni);Temple",
"Temple (-> Gallieni);Republique",
"Republique (-> Gallieni);Parmentier",
"Parmentier (-> Gallieni);Rue Saint-Maur",
"Rue Saint-Maur (-> Gallieni);Pere Lachaise",
"Pere Lachaise (-> Gallieni);Gambetta",
"Gambetta (-> Gallieni);Porte de Bagnolet",
"Porte de Bagnolet (-> Gallieni);Gallieni",
"Gallieni (-> Pont de Levallois);Porte de Bagnolet",
"Porte de Bagnolet (-> Pont de Levallois);Gambetta",
"Gambetta (-> Pont de Levallois);Pere Lachaise",
"Pere Lachaise (-> Pont de Levallois);Rue Saint-Maur",
"Rue Saint-Maur (-> Pont de Levallois);Parmentier",
"Parmentier (-> Pont de Levallois);Republique",
"Republique (-> Pont de Levallois);Temple",
"Temple (-> Pont de Levallois);Arts et Metiers",
"Arts et Metiers (-> Pont de Levallois);Reaumur - Sebastopol",
"Reaumur - Sebastopol (-> Pont de Levallois);Sentier",
"Sentier (-> Pont de Levallois);Bourse",
"Bourse (-> Pont de Levallois);Quatre Septembre",
"Quatre Septembre (-> Pont de Levallois);Opera",
"Opera (-> Pont de Levallois);Havre - Caumartin",
"Havre - Caumartin (-> Pont de Levallois);Saint-Lazare",
"Saint-Lazare (-> Pont de Levallois);Europe",
"Europe (-> Pont de Levallois);Villiers",
"Villiers (-> Pont de Levallois);Malesherbes",
"Malesherbes (-> Pont de Levallois);Wagram",
"Wagram (-> Pont de Levallois);Pereire",
"Pereire (-> Pont de Levallois);Porte de Champerret",
"Porte de Champerret (-> Pont de Levallois);Louise Michel",
"Louise Michel (-> Pont de Levallois);Anatole France",
"Anatole France (-> Pont de Levallois);Pont de Levallois - Becon",
"Gambetta (-> Porte des Lilas);Pelleport",
"Pelleport (-> Porte des Lilas);Saint-Fargeau",
"Saint-Fargeau (-> Porte des Lilas);Porte des Lilas",
"Porte des Lilas (-> Gambetta);Saint-Fargeau",
"Saint-Fargeau (-> Gambetta);Pelleport",
"Pelleport (-> Gambetta);Gambetta",
"Porte de Clignancourt (-> Bagneux);Simplon",
"Simplon (-> Bagneux);Marcadet - Poissonniers",
"Marcadet - Poissonniers (-> Bagneux);Chateau Rouge",
"Chateau Rouge (-> Bagneux);Barbes - Rochechouart",
"Barbes - Rochechouart (-> Bagneux);Gare du Nord",
"Gare du Nord (-> Bagneux);Gare de l'Est",
"Gare de l'Est (-> Bagneux);Chateau d'Eau",
"Chateau d'Eau (-> Bagneux);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Bagneux);Reaumur - Sebastopol",
"Reaumur - Sebastopol (-> Bagneux);Etienne Marcel",
"Etienne Marcel (-> Bagneux);Les Halles",
"Les Halles (-> Bagneux);Chatelet",
"Chatelet (-> Bagneux);Cite",
"Cite (-> Bagneux);Saint-Michel",
"Saint-Michel (-> Bagneux);Odeon",
"Odeon (-> Bagneux);Saint-Germain des Pres",
"Saint-Germain des Pres (-> Bagneux);Saint-Sulpice",
"Saint-Sulpice (-> Bagneux);Saint-Placide",
"Saint-Placide (-> Bagneux);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Bagneux);Vavin",
"Vavin (-> Bagneux);Raspail",
"Raspail (-> Bagneux);Denfert Rochereau",
"Denfert Rochereau (-> Bagneux);Mouton Duvernet",
"Mouton Duvernet (-> Bagneux);Alesia",
"Alesia (-> Bagneux);Porte d'Orleans",
"Porte d'Orleans (-> Bagneux);Mairie de Montrouge",
"Mairie de Montrouge (-> Bagneux);Barbara",
"Barbara (-> Bagneux);Bagneux Lucie Aubrac",
"Bagneux Lucie Aubrac (-> Porte de Clignancourt);Barbara",
"Barbara (-> Porte de Clignancourt);Mairie de Montrouge",
"Mairie de Montrouge (-> Porte de Clignancourt);Porte d'Orleans",
"Porte d'Orleans (-> Porte de Clignancourt);Alesia",
"Alesia (-> Porte de Clignancourt);Mouton Duvernet",
"Mouton Duvernet (-> Porte de Clignancourt);Denfert Rochereau",
"Denfert Rochereau (-> Porte de Clignancourt);Raspail",
"Raspail (-> Porte de Clignancourt);Vavin",
"Vavin (-> Porte de Clignancourt);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Porte de Clignancourt);Saint-Placide",
"Saint-Placide (-> Porte de Clignancourt);Saint-Sulpice",
"Saint-Sulpice (-> Porte de Clignancourt);Saint-Germain des Pres",
"Saint-Germain des Pres (-> Porte de Clignancourt);Odeon",
"Odeon (-> Porte de Clignancourt);Saint-Michel",
"Saint-Michel (-> Porte de Clignancourt);Cite",
"Cite (-> Porte de Clignancourt);Chatelet",
"Chatelet (-> Porte de Clignancourt);Les Halles",
"Les Halles (-> Porte de Clignancourt);Etienne Marcel",
"Etienne Marcel (-> Porte de Clignancourt);Reaumur - Sebastopol",
"Reaumur - Sebastopol (-> Porte de Clignancourt);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Porte de Clignancourt);Chateau d'Eau",
"Chateau d'Eau (-> Porte de Clignancourt);Gare de l'Est",
"Gare de l'Est (-> Porte de Clignancourt);Gare du Nord",
"Gare du Nord (-> Porte de Clignancourt);Barbes - Rochechouart",
"Barbes - Rochechouart (-> Porte de Clignancourt);Chateau Rouge",
"Chateau Rouge (-> Porte de Clignancourt);Marcadet - Poissonniers",
"Marcadet - Poissonniers (-> Porte de Clignancourt);Simplon",
"Simplon (-> Porte de Clignancourt);Porte de Clignancourt",
"Bobigny - Pablo Picasso (-> Place d'Italie);Bobigny - Pantin - Raymond Queneau",
"Bobigny - Pantin - Raymond Queneau (-> Place d'Italie);Eglise de Pantin",
"Eglise de Pantin (-> Place d'Italie);Hoche",
"Hoche (-> Place d'Italie);Porte de Pantin",
"Porte de Pantin (-> Place d'Italie);Ourcq",
"Ourcq (-> Place d'Italie);Laumiere",
"Laumiere (-> Place d'Italie);Jaures",
"Jaures (-> Place d'Italie);Stalingrad",
"Stalingrad (-> Place d'Italie);Gare du Nord",
"Gare du Nord (-> Place d'Italie);Gare de l'Est",
"Gare de l'Est (-> Place d'Italie);Jacques Bonsergent",
"Jacques Bonsergent (-> Place d'Italie);Republique",
"Republique (-> Place d'Italie);Oberkampf",
"Oberkampf (-> Place d'Italie);Richard Lenoir",
"Richard Lenoir (-> Place d'Italie);Breguet - Sabin",
"Breguet - Sabin (-> Place d'Italie);Bastille",
"Bastille (-> Place d'Italie);Quai de la Rapee",
"Quai de la Rapee (-> Place d'Italie);Gare d'Austerlitz",
"Gare d'Austerlitz (-> Place d'Italie);Saint-Marcel",
"Saint-Marcel (-> Place d'Italie);Campo Formio",
"Campo Formio (-> Place d'Italie);Place d'Italie",
"Place d'Italie (-> Bobigny);Campo Formio",
"Campo Formio (-> Bobigny);Saint-Marcel",
"Saint-Marcel (-> Bobigny);Gare d'Austerlitz",
"Gare d'Austerlitz (-> Bobigny);Quai de la Rapee",
"Quai de la Rapee (-> Bobigny);Bastille",
"Bastille (-> Bobigny);Breguet - Sabin",
"Breguet - Sabin (-> Bobigny);Richard Lenoir",
"Richard Lenoir (-> Bobigny);Oberkampf",
"Oberkampf (-> Bobigny);Republique",
"Republique (-> Bobigny);Jacques Bonsergent",
"Jacques Bonsergent (-> Bobigny);Gare de l'Est",
"Gare de l'Est (-> Bobigny);Gare du Nord",
"Gare du Nord (-> Bobigny);Stalingrad",
"Stalingrad (-> Bobigny);Jaures",
"Jaures (-> Bobigny);Laumiere",
"Laumiere (-> Bobigny);Ourcq",
"Ourcq (-> Bobigny);Porte de Pantin",
"Porte de Pantin (-> Bobigny);Hoche",
"Hoche (-> Bobigny);Eglise de Pantin",
"Eglise de Pantin (-> Bobigny);Bobigny - Pantin - Raymond Queneau",
"Bobigny - Pantin - Raymond Queneau (-> Bobigny);Bobigny - Pablo Picasso",
"Charles de Gaulle - Etoile (-> Nation);Kleber",
"Kleber (-> Nation);Boissiere",
"Boissiere (-> Nation);Trocadero",
"Trocadero (-> Nation);Passy",
"Passy (-> Nation);Bir Hakeim",
"Bir Hakeim (-> Nation);Dupleix",
"Dupleix (-> Nation);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Nation);Cambronne",
"Cambronne (-> Nation);Sevres - Lecourbe",
"Sevres - Lecourbe (-> Nation);Pasteur",
"Pasteur (-> Nation);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Nation);Edgar Quinet",
"Edgar Quinet (-> Nation);Raspail",
"Raspail (-> Nation);Denfert Rochereau",
"Denfert Rochereau (-> Nation);Saint-Jacques",
"Saint-Jacques (-> Nation);Glaciere",
"Glaciere (-> Nation);Corvisart",
"Corvisart (-> Nation);Place d'Italie",
"Place d'Italie (-> Nation);Nationale",
"Nationale (-> Nation);Chevaleret",
"Chevaleret (-> Nation);Quai de la Gare",
"Quai de la Gare (-> Nation);Bercy",
"Bercy (-> Nation);Dugommier",
"Dugommier (-> Nation);Daumesnil",
"Daumesnil (-> Nation);Bel Air",
"Bel Air (-> Nation);Picpus",
"Picpus (-> Nation);Nation",
"Nation (-> Etoile);Picpus",
"Picpus (-> Etoile);Bel Air",
"Bel Air (-> Etoile);Daumesnil",
"Daumesnil (-> Etoile);Dugommier",
"Dugommier (-> Etoile);Bercy",
"Bercy (-> Etoile);Quai de la Gare",
"Quai de la Gare (-> Etoile);Chevaleret",
"Chevaleret (-> Etoile);Nationale",
"Nationale (-> Etoile);Place d'Italie",
"Place d'Italie (-> Etoile);Corvisart",
"Corvisart (-> Etoile);Glaciere",
"Glaciere (-> Etoile);Saint-Jacques",
"Saint-Jacques (-> Etoile);Denfert Rochereau",
"Denfert Rochereau (-> Etoile);Raspail",
"Raspail (-> Etoile);Edgar Quinet",
"Edgar Quinet (-> Etoile);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Etoile);Pasteur",
"Pasteur (-> Etoile);Sevres - Lecourbe",
"Sevres - Lecourbe (-> Etoile);Cambronne",
"Cambronne (-> Etoile);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Etoile);Dupleix",
"Dupleix (-> Etoile);Bir Hakeim",
"Bir Hakeim (-> Etoile);Passy",
"Passy (-> Etoile);Trocadero",
"Trocadero (-> Etoile);Boissiere",
"Boissiere (-> Etoile);Kleber",
"Kleber (-> Etoile);Charles de Gaulle - Etoile",
"La Courneuve - 8 Mai 1945 (-> Mairie d'Ivry);Fort d'Aubervilliers",
"Fort d'Aubervilliers (-> Mairie d'Ivry);Aubervilliers - Pantin Quatre Chemins",
"Aubervilliers - Pantin Quatre Chemins (-> Mairie d'Ivry);Porte de la Villette",
"Porte de la Villette (-> Mairie d'Ivry);Corentin Cariou",
"Corentin Cariou (-> Mairie d'Ivry);Crimee",
"Crimee (-> Mairie d'Ivry);Riquet",
"Riquet (-> Mairie d'Ivry);Stalingrad",
"Stalingrad (-> Mairie d'Ivry);Louis Blanc",
"Louis Blanc (-> Mairie d'Ivry);Chateau Landon",
"Chateau Landon (-> Mairie d'Ivry);Gare de l'Est",
"Gare de l'Est (-> Mairie d'Ivry);Poissonniere",
"Poissonniere (-> Mairie d'Ivry);Cadet",
"Cadet (-> Mairie d'Ivry);Le Peletier",
"Le Peletier (-> Mairie d'Ivry);Chaussee d'Antin - La Fayette",
"Chaussee d'Antin - La Fayette (-> Mairie d'Ivry);Opera",
"Opera (-> Mairie d'Ivry);Pyramides",
"Pyramides (-> Mairie d'Ivry);Palais Royal - Musee du Louvre",
"Palais Royal - Musee du Louvre (-> Mairie d'Ivry);Pont Neuf",
"Pont Neuf (-> Mairie d'Ivry);Chatelet",
"Chatelet (-> Mairie d'Ivry);Pont Marie",
"Pont Marie (-> Mairie d'Ivry);Sully - Morland",
"Sully - Morland (-> Mairie d'Ivry);Jussieu",
"Jussieu (-> Mairie d'Ivry);Place Monge",
"Place Monge (-> Mairie d'Ivry);Censier - Daubenton",
"Censier - Daubenton (-> Mairie d'Ivry);Les Gobelins",
"Les Gobelins (-> Mairie d'Ivry);Place d'Italie",
"Place d'Italie (-> Mairie d'Ivry);Tolbiac",
"Tolbiac (-> Mairie d'Ivry);Maison Blanche",
"Maison Blanche (-> Mairie d'Ivry);Porte d'Italie",
"Porte d'Italie (-> Mairie d'Ivry);Porte de Choisy",
"Porte de Choisy (-> Mairie d'Ivry);Porte d'Ivry",
"Porte d'Ivry (-> Mairie d'Ivry);Pierre et Marie Curie",
"Pierre et Marie Curie (-> Mairie d'Ivry);Mairie d'Ivry",
"Mairie d'Ivry (-> La Courneuve);Pierre et Marie Curie",
"Pierre et Marie Curie (-> La Courneuve);Porte d'Ivry",
"Porte d'Ivry (-> La Courneuve);Porte de Choisy",
"Porte de Choisy (-> La Courneuve);Porte d'Italie",
"Porte d'Italie (-> La Courneuve);Maison Blanche",
"Maison Blanche (-> La Courneuve);Tolbiac",
"Tolbiac (-> La Courneuve);Place d'Italie",
"Place d'Italie (-> La Courneuve);Les Gobelins",
"Les Gobelins (-> La Courneuve);Censier - Daubenton",
"Censier - Daubenton (-> La Courneuve);Place Monge",
"Place Monge (-> La Courneuve);Jussieu",
"Jussieu (-> La Courneuve);Sully - Morland",
"Sully - Morland (-> La Courneuve);Pont Marie",
"Pont Marie (-> La Courneuve);Chatelet",
"Chatelet (-> La Courneuve);Pont Neuf",
"Pont Neuf (-> La Courneuve);Palais Royal - Musee du Louvre",
"Palais Royal - Musee du Louvre (-> La Courneuve);Pyramides",
"Pyramides (-> La Courneuve);Opera",
"Opera (-> La Courneuve);Chaussee d'Antin - La Fayette",
"Chaussee d'Antin - La Fayette (-> La Courneuve);Le Peletier",
"Le Peletier (-> La Courneuve);Cadet",
"Cadet (-> La Courneuve);Poissonniere",
"Poissonniere (-> La Courneuve);Gare de l'Est",
"Gare de l'Est (-> La Courneuve);Chateau Landon",
"Chateau Landon (-> La Courneuve);Louis Blanc",
"Louis Blanc (-> La Courneuve);Stalingrad",
"Stalingrad (-> La Courneuve);Riquet",
"Riquet (-> La Courneuve);Crimee",
"Crimee (-> La Courneuve);Corentin Cariou",
"Corentin Cariou (-> La Courneuve);Porte de la Villette",
"Porte de la Villette (-> La Courneuve);Aubervilliers - Pantin Quatre Chemins",
"Aubervilliers - Pantin Quatre Chemins (-> La Courneuve);Fort d'Aubervilliers",
"Fort d'Aubervilliers (-> La Courneuve);La Courneuve - 8 Mai 1945",
"Maison Blanche (-> Villejuif);Le Kremlin Bicetre",
"Le Kremlin Bicetre (-> Villejuif);Villejuif - Leo Lagrange",
"Villejuif - Leo Lagrange (-> Villejuif);Villejuif - Paul Vaillant-Couturier",
"Villejuif - Paul Vaillant-Couturier (-> Villejuif);Villejuif - Louis Aragon",
"Villejuif - Louis Aragon (-> Maison Blanche);Villejuif - Paul Vaillant-Couturier",
"Villejuif - Paul Vaillant-Couturier (-> Maison Blanche);Villejuif - Leo Lagrange",
"Villejuif - Leo Lagrange (-> Maison Blanche);Le Kremlin Bicetre",
"Le Kremlin Bicetre (-> Maison Blanche);Maison Blanche",
"Pre-Saint-Gervais (-> Louis Blanc);Danube",
"Danube (-> Louis Blanc);Botzaris",
"Botzaris (-> Louis Blanc);Buttes Chaumont",
"Buttes Chaumont (-> Louis Blanc);Bolivar",
"Bolivar (-> Louis Blanc);Jaures",
"Jaures (-> Louis Blanc);Louis Blanc",
"Louis Blanc (-> Pre-Saint-Gervais);Jaures",
"Jaures (-> Pre-Saint-Gervais);Bolivar",
"Bolivar (-> Pre-Saint-Gervais);Buttes Chaumont",
"Buttes Chaumont (-> Pre-Saint-Gervais);Botzaris",
"Botzaris (-> Pre-Saint-Gervais);Place des Fetes",
"Place des Fetes (-> Pre-Saint-Gervais);Pre-Saint-Gervais",
"Balard (-> Creteil);Lourmel",
"Lourmel (-> Creteil);Boucicaut",
"Boucicaut (-> Creteil);Felix Faure",
"Felix Faure (-> Creteil);Commerce",
"Commerce (-> Creteil);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Creteil);Ecole Militaire",
"Ecole Militaire (-> Creteil);La Tour Maubourg",
"La Tour Maubourg (-> Creteil);Invalides",
"Invalides (-> Creteil);Concorde",
"Concorde (-> Creteil);Madeleine",
"Madeleine (-> Creteil);Opera",
"Opera (-> Creteil);Richelieu - Drouot",
"Richelieu - Drouot (-> Creteil);Grands Boulevards",
"Grands Boulevards (-> Creteil);Bonne Nouvelle",
"Bonne Nouvelle (-> Creteil);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Creteil);Republique",
"Republique (-> Creteil);Filles du Calvaire",
"Filles du Calvaire (-> Creteil);Saint-Sebastien - Froissart",
"Saint-Sebastien - Froissart (-> Creteil);Chemin Vert",
"Chemin Vert (-> Creteil);Bastille",
"Bastille (-> Creteil);Ledru Rollin",
"Ledru Rollin (-> Creteil);Faidherbe - Chaligny",
"Faidherbe - Chaligny (-> Creteil);Reuilly - Diderot",
"Reuilly - Diderot (-> Creteil);Montgallet",
"Montgallet (-> Creteil);Daumesnil",
"Daumesnil (-> Creteil);Michel Bizot",
"Michel Bizot (-> Creteil);Porte Doree",
"Porte Doree (-> Creteil);Porte de Charenton",
"Porte de Charenton (-> Creteil);Liberte",
"Liberte (-> Creteil);Charenton - Ecoles",
"Charenton - Ecoles (-> Creteil);Ecole Veterinaire de Maisons-Alfort",
"Ecole Veterinaire de Maisons-Alfort (-> Creteil);Maisons-Alfort - Stade",
"Maisons-Alfort - Stade (-> Creteil);Maisons-Alfort - Les Juilliottes",
"Maisons-Alfort - Les Juilliottes (-> Creteil);Creteil - L'Echat",
"Creteil - L'Echat (-> Creteil);Creteil - Universite",
"Creteil - Universite (-> Creteil);Creteil - Prefecture",
"Creteil - Prefecture (-> Creteil);Creteil - Pointe du Lac",
"Creteil - Pointe du Lac (-> Balard);Creteil - Prefecture",
"Creteil - Prefecture (-> Balard);Creteil - Universite",
"Creteil - Universite (-> Balard);Creteil - L'Echat",
"Creteil - L'Echat (-> Balard);Maisons-Alfort - Les Juilliottes",
"Maisons-Alfort - Les Juilliottes (-> Balard);Maisons-Alfort - Stade",
"Maisons-Alfort - Stade (-> Balard);Ecole Veterinaire de Maisons-Alfort",
"Ecole Veterinaire de Maisons-Alfort (-> Balard);Charenton - Ecoles",
"Charenton - Ecoles (-> Balard);Liberte",
"Liberte (-> Balard);Porte de Charenton",
"Porte de Charenton (-> Balard);Porte Doree",
"Porte Doree (-> Balard);Michel Bizot",
"Michel Bizot (-> Balard);Daumesnil",
"Daumesnil (-> Balard);Montgallet",
"Montgallet (-> Balard);Reuilly - Diderot",
"Reuilly - Diderot (-> Balard);Faidherbe - Chaligny",
"Faidherbe - Chaligny (-> Balard);Ledru Rollin",
"Ledru Rollin (-> Balard);Bastille",
"Bastille (-> Balard);Chemin Vert",
"Chemin Vert (-> Balard);Saint-Sebastien - Froissart",
"Saint-Sebastien - Froissart (-> Balard);Filles du Calvaire",
"Filles du Calvaire (-> Balard);Republique",
"Republique (-> Balard);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Balard);Bonne Nouvelle",
"Bonne Nouvelle (-> Balard);Grands Boulevards",
"Grands Boulevards (-> Balard);Richelieu - Drouot",
"Richelieu - Drouot (-> Balard);Opera",
"Opera (-> Balard);Madeleine",
"Madeleine (-> Balard);Concorde",
"Concorde (-> Balard);Invalides",
"Invalides (-> Balard);La Tour Maubourg",
"La Tour Maubourg (-> Balard);Ecole Militaire",
"Ecole Militaire (-> Balard);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Balard);Commerce",
"Commerce (-> Balard);Felix Faure",
"Felix Faure (-> Balard);Boucicaut",
"Boucicaut (-> Balard);Lourmel",
"Lourmel (-> Balard);Balard",
"Pont de Sevres (-> Mairie de Montreuil);Billancourt",
"Billancourt (-> Mairie de Montreuil);Marcel Sembat",
"Marcel Sembat (-> Mairie de Montreuil);Porte de Saint-Cloud",
"Porte de Saint-Cloud (-> Mairie de Montreuil);Exelmans",
"Exelmans (-> Mairie de Montreuil);Michel-Ange - Molitor",
"Michel-Ange - Molitor (-> Mairie de Montreuil);Michel-Ange - Auteuil",
"Michel-Ange - Auteuil (-> Mairie de Montreuil);Jasmin",
"Jasmin (-> Mairie de Montreuil);Ranelagh",
"Ranelagh (-> Mairie de Montreuil);La Muette",
"La Muette (-> Mairie de Montreuil);Rue de la Pompe",
"Rue de la Pompe (-> Mairie de Montreuil);Trocadero",
"Trocadero (-> Mairie de Montreuil);Iena",
"Iena (-> Mairie de Montreuil);Alma - Marceau",
"Alma - Marceau (-> Mairie de Montreuil);Franklin-D. Roosevelt",
"Franklin-D. Roosevelt (-> Mairie de Montreuil);Saint-Philippe du Roule",
"Saint-Philippe du Roule (-> Mairie de Montreuil);Miromesnil",
"Miromesnil (-> Mairie de Montreuil);Saint-Augustin",
"Saint-Augustin (-> Mairie de Montreuil);Havre - Caumartin",
"Havre - Caumartin (-> Mairie de Montreuil);Chaussee d'Antin - La Fayette",
"Chaussee d'Antin - La Fayette (-> Mairie de Montreuil);Richelieu - Drouot",
"Richelieu - Drouot (-> Mairie de Montreuil);Grands Boulevards",
"Grands Boulevards (-> Mairie de Montreuil);Bonne Nouvelle",
"Bonne Nouvelle (-> Mairie de Montreuil);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Mairie de Montreuil);Republique",
"Republique (-> Mairie de Montreuil);Oberkampf",
"Oberkampf (-> Mairie de Montreuil);Saint-Ambroise",
"Saint-Ambroise (-> Mairie de Montreuil);Voltaire",
"Voltaire (-> Mairie de Montreuil);Charonne",
"Charonne (-> Mairie de Montreuil);Rue des Boulets",
"Rue des Boulets (-> Mairie de Montreuil);Nation",
"Nation (-> Mairie de Montreuil);Buzenval",
"Buzenval (-> Mairie de Montreuil);Maraichers",
"Maraichers (-> Mairie de Montreuil);Porte de Montreuil",
"Porte de Montreuil (-> Mairie de Montreuil);Robespierre",
"Robespierre (-> Mairie de Montreuil);Croix de Chavaux",
"Croix de Chavaux (-> Mairie de Montreuil);Mairie de Montreuil",
"Mairie de Montreuil (-> Pont de Sevres);Croix de Chavaux",
"Croix de Chavaux (-> Pont de Sevres);Robespierre",
"Robespierre (-> Pont de Sevres);Porte de Montreuil",
"Porte de Montreuil (-> Pont de Sevres);Maraichers",
"Maraichers (-> Pont de Sevres);Buzenval",
"Buzenval (-> Pont de Sevres);Nation",
"Nation (-> Pont de Sevres);Rue des Boulets",
"Rue des Boulets (-> Pont de Sevres);Charonne",
"Charonne (-> Pont de Sevres);Voltaire",
"Voltaire (-> Pont de Sevres);Saint-Ambroise",
"Saint-Ambroise (-> Pont de Sevres);Oberkampf",
"Oberkampf (-> Pont de Sevres);Republique",
"Republique (-> Pont de Sevres);Strasbourg - Saint-Denis",
"Strasbourg - Saint-Denis (-> Pont de Sevres);Bonne Nouvelle",
"Bonne Nouvelle (-> Pont de Sevres);Grands Boulevards",
"Grands Boulevards (-> Pont de Sevres);Richelieu - Drouot",
"Richelieu - Drouot (-> Pont de Sevres);Chaussee d'Antin - La Fayette",
"Chaussee d'Antin - La Fayette (-> Pont de Sevres);Havre - Caumartin",
"Havre - Caumartin (-> Pont de Sevres);Saint-Augustin",
"Saint-Augustin (-> Pont de Sevres);Miromesnil",
"Miromesnil (-> Pont de Sevres);Saint-Philippe du Roule",
"Saint-Philippe du Roule (-> Pont de Sevres);Franklin-D. Roosevelt",
"Franklin-D. Roosevelt (-> Pont de Sevres);Alma - Marceau",
"Alma - Marceau (-> Pont de Sevres);Iena",
"Iena (-> Pont de Sevres);Trocadero",
"Trocadero (-> Pont de Sevres);Rue de la Pompe",
"Rue de la Pompe (-> Pont de Sevres);La Muette",
"La Muette (-> Pont de Sevres);Ranelagh",
"Ranelagh (-> Pont de Sevres);Jasmin",
"Jasmin (-> Pont de Sevres);Michel-Ange - Auteuil",
"Michel-Ange - Auteuil (-> Pont de Sevres);Michel-Ange - Molitor",
"Michel-Ange - Molitor (-> Pont de Sevres);Exelmans",
"Exelmans (-> Pont de Sevres);Porte de Saint-Cloud",
"Porte de Saint-Cloud (-> Pont de Sevres);Marcel Sembat",
"Marcel Sembat (-> Pont de Sevres);Billancourt",
"Billancourt (-> Pont de Sevres);Pont de Sevres",
"Boulogne - Pont de Saint-Cloud (-> Austerlitz);Boulogne - Jean Jaures",
"Boulogne - Jean Jaures (-> Austerlitz);Michel-Ange - Molitor",
"Michel-Ange - Molitor (-> Austerlitz);Chardon - Lagache",
"Chardon - Lagache (-> Austerlitz);Mirabeau",
"Mirabeau (-> Austerlitz);Javel",
"Javel (-> Austerlitz);Charles Michels",
"Charles Michels (-> Austerlitz);Avenue Emile Zola",
"Avenue Emile Zola (-> Austerlitz);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Austerlitz);Segur",
"Segur (-> Austerlitz);Duroc",
"Duroc (-> Austerlitz);Vaneau",
"Vaneau (-> Austerlitz);Sevres - Babylone",
"Sevres - Babylone (-> Austerlitz);Mabillon",
"Mabillon (-> Austerlitz);Odeon",
"Odeon (-> Austerlitz);Cluny - La Sorbonne",
"Cluny - La Sorbonne (-> Austerlitz);Maubert - Mutualite",
"Maubert - Mutualite (-> Austerlitz);Cardinal Lemoine",
"Cardinal Lemoine (-> Austerlitz);Jussieu",
"Jussieu (-> Austerlitz);Gare d'Austerlitz",
"Gare d'Austerlitz (-> Boulogne);Jussieu",
"Jussieu (-> Boulogne);Cardinal Lemoine",
"Cardinal Lemoine (-> Boulogne);Maubert - Mutualite",
"Maubert - Mutualite (-> Boulogne);Cluny - La Sorbonne",
"Cluny - La Sorbonne (-> Boulogne);Odeon",
"Odeon (-> Boulogne);Mabillon",
"Mabillon (-> Boulogne);Sevres - Babylone",
"Sevres - Babylone (-> Boulogne);Vaneau",
"Vaneau (-> Boulogne);Duroc",
"Duroc (-> Boulogne);Segur",
"Segur (-> Boulogne);La Motte-Picquet - Grenelle",
"La Motte-Picquet - Grenelle (-> Boulogne);Avenue Emile Zola",
"Avenue Emile Zola (-> Boulogne);Charles Michels",
"Charles Michels (-> Boulogne);Javel",
"Javel (-> Boulogne);Eglise d'Auteuil",
"Eglise d'Auteuil (-> Boulogne);Michel-Ange - Auteuil",
"Michel-Ange - Auteuil (-> Boulogne);Porte d'Auteuil",
"Porte d'Auteuil (-> Boulogne);Boulogne - Jean Jaures",
"Boulogne - Jean Jaures (-> Boulogne);Boulogne - Pont de Saint-Cloud",
"Mairie des Lilas (-> Chatelet);Porte des Lilas",
"Porte des Lilas (-> Chatelet);Telegraphe",
"Telegraphe (-> Chatelet);Place des Fetes",
"Place des Fetes (-> Chatelet);Jourdain",
"Jourdain (-> Chatelet);Pyrenees",
"Pyrenees (-> Chatelet);Belleville",
"Belleville (-> Chatelet);Goncourt",
"Goncourt (-> Chatelet);Republique",
"Republique (-> Chatelet);Arts et Metiers",
"Arts et Metiers (-> Chatelet);Rambuteau",
"Rambuteau (-> Chatelet);Hotel de Ville",
"Hotel de Ville (-> Chatelet);Chatelet",
"Chatelet (-> Mairie des Lilas);Hotel de Ville",
"Hotel de Ville (-> Mairie des Lilas);Rambuteau",
"Rambuteau (-> Mairie des Lilas);Arts et Metiers",
"Arts et Metiers (-> Mairie des Lilas);Republique",
"Republique (-> Mairie des Lilas);Goncourt",
"Goncourt (-> Mairie des Lilas);Belleville",
"Belleville (-> Mairie des Lilas);Pyrenees",
"Pyrenees (-> Mairie des Lilas);Jourdain",
"Jourdain (-> Mairie des Lilas);Place des Fetes",
"Place des Fetes (-> Mairie des Lilas);Telegraphe",
"Telegraphe (-> Mairie des Lilas);Porte des Lilas",
"Porte des Lilas (-> Mairie des Lilas);Mairie des Lilas",
"Mairie d'Aubervilliers (-> Mairie d'Issy);Aime Cesaire",
"Aime Cesaire (-> Mairie d'Issy);Front Populaire",
"Front Populaire (-> Mairie d'Issy);Porte de la Chapelle",
"Porte de la Chapelle (-> Mairie d'Issy);Marx Dormoy",
"Marx Dormoy (-> Mairie d'Issy);Marcadet - Poissonniers",
"Marcadet - Poissonniers (-> Mairie d'Issy);Jules Joffrin",
"Jules Joffrin (-> Mairie d'Issy);Lamarck - Caulaincourt",
"Lamarck - Caulaincourt (-> Mairie d'Issy);Abbesses",
"Abbesses (-> Mairie d'Issy);Pigalle",
"Pigalle (-> Mairie d'Issy);Saint-Georges",
"Saint-Georges (-> Mairie d'Issy);Notre-Dame de Lorette",
"Notre-Dame de Lorette (-> Mairie d'Issy);Trinite - d'Estienne d'Orves",
"Trinite - d'Estienne d'Orves (-> Mairie d'Issy);Saint-Lazare",
"Saint-Lazare (-> Mairie d'Issy);Madeleine",
"Madeleine (-> Mairie d'Issy);Concorde",
"Concorde (-> Mairie d'Issy);Assemblee Nationale",
"Assemblee Nationale (-> Mairie d'Issy);Solferino",
"Solferino (-> Mairie d'Issy);Rue du Bac",
"Rue du Bac (-> Mairie d'Issy);Sevres - Babylone",
"Sevres - Babylone (-> Mairie d'Issy);Rennes",
"Rennes (-> Mairie d'Issy);Notre-Dame des Champs",
"Notre-Dame des Champs (-> Mairie d'Issy);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Mairie d'Issy);Falguiere",
"Falguiere (-> Mairie d'Issy);Pasteur",
"Pasteur (-> Mairie d'Issy);Volontaires",
"Volontaires (-> Mairie d'Issy);Vaugirard",
"Vaugirard (-> Mairie d'Issy);Convention",
"Convention (-> Mairie d'Issy);Porte de Versailles",
"Porte de Versailles (-> Mairie d'Issy);Corentin Celton",
"Corentin Celton (-> Mairie d'Issy);Mairie d'Issy",
"Mairie d'Issy (-> Mairie d'Aubervilliers);Corentin Celton",
"Corentin Celton (-> Mairie d'Aubervilliers);Porte de Versailles",
"Porte de Versailles (-> Mairie d'Aubervilliers);Convention",
"Convention (-> Mairie d'Aubervilliers);Vaugirard",
"Vaugirard (-> Mairie d'Aubervilliers);Volontaires",
"Volontaires (-> Mairie d'Aubervilliers);Pasteur",
"Pasteur (-> Mairie d'Aubervilliers);Falguiere",
"Falguiere (-> Mairie d'Aubervilliers);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Mairie d'Aubervilliers);Notre-Dame des Champs",
"Notre-Dame des Champs (-> Mairie d'Aubervilliers);Rennes",
"Rennes (-> Mairie d'Aubervilliers);Sevres - Babylone",
"Sevres - Babylone (-> Mairie d'Aubervilliers);Rue du Bac",
"Rue du Bac (-> Mairie d'Aubervilliers);Solferino",
"Solferino (-> Mairie d'Aubervilliers);Assemblee Nationale",
"Assemblee Nationale (-> Mairie d'Aubervilliers);Concorde",
"Concorde (-> Mairie d'Aubervilliers);Madeleine",
"Madeleine (-> Mairie d'Aubervilliers);Saint-Lazare",
"Saint-Lazare (-> Mairie d'Aubervilliers);Trinite - d'Estienne d'Orves",
"Trinite - d'Estienne d'Orves (-> Mairie d'Aubervilliers);Notre-Dame de Lorette",
"Notre-Dame de Lorette (-> Mairie d'Aubervilliers);Saint-Georges",
"Saint-Georges (-> Mairie d'Aubervilliers);Pigalle",
"Pigalle (-> Mairie d'Aubervilliers);Abbesses",
"Abbesses (-> Mairie d'Aubervilliers);Lamarck - Caulaincourt",
"Lamarck - Caulaincourt (-> Mairie d'Aubervilliers);Jules Joffrin",
"Jules Joffrin (-> Mairie d'Aubervilliers);Marcadet - Poissonniers",
"Marcadet - Poissonniers (-> Mairie d'Aubervilliers);Marx Dormoy",
"Marx Dormoy (-> Mairie d'Aubervilliers);Porte de la Chapelle",
"Porte de la Chapelle (-> Mairie d'Aubervilliers);Front Populaire",
"Front Populaire (-> Mairie d'Aubervilliers);Aime Cesaire",
"Aime Cesaire (-> Mairie d'Aubervilliers);Mairie d'Aubervilliers",
"Saint-Denis - Universite (-> Chatillon - Montrouge);Basilique de Saint-Denis",
"Basilique de Saint-Denis (-> Chatillon - Montrouge);Saint-Denis - Porte de Paris",
"Saint-Denis - Porte de Paris (-> Chatillon - Montrouge);Carrefour Pleyel",
"Carrefour Pleyel (-> Chatillon - Montrouge);Mairie de Saint-Ouen",
"Mairie de Saint-Ouen (-> Chatillon - Montrouge);Garibaldi",
"Garibaldi (-> Chatillon - Montrouge);Porte de Saint-Ouen",
"Porte de Saint-Ouen (-> Chatillon - Montrouge);Guy Moquet",
"Guy Moquet (-> Chatillon - Montrouge);La Fourche",
"La Fourche (-> Chatillon - Montrouge);Place de Clichy",
"Place de Clichy (-> Chatillon - Montrouge);Liege",
"Liege (-> Chatillon - Montrouge);Saint-Lazare",
"Saint-Lazare (-> Chatillon - Montrouge);Miromesnil",
"Miromesnil (-> Chatillon - Montrouge);Champs Elysees - Clemenceau",
"Champs Elysees - Clemenceau (-> Chatillon - Montrouge);Invalides",
"Invalides (-> Chatillon - Montrouge);Varenne",
"Varenne (-> Chatillon - Montrouge);Saint-Francois-Xavier",
"Saint-Francois-Xavier (-> Chatillon - Montrouge);Duroc",
"Duroc (-> Chatillon - Montrouge);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Chatillon - Montrouge);Gaite",
"Gaite (-> Chatillon - Montrouge);Pernety",
"Pernety (-> Chatillon - Montrouge);Plaisance",
"Plaisance (-> Chatillon - Montrouge);Porte de Vanves",
"Porte de Vanves (-> Chatillon - Montrouge);Malakoff - Plateau de Vanves",
"Malakoff - Plateau de Vanves (-> Chatillon - Montrouge);Malakoff - Rue Etienne Dolet",
"Malakoff - Rue Etienne Dolet (-> Chatillon - Montrouge);Chatillon - Montrouge",
"Chatillon - Montrouge (-> Saint-Denis);Malakoff - Rue Etienne Dolet",
"Malakoff - Rue Etienne Dolet (-> Saint-Denis);Malakoff - Plateau de Vanves",
"Malakoff - Plateau de Vanves (-> Saint-Denis);Porte de Vanves",
"Porte de Vanves (-> Saint-Denis);Plaisance",
"Plaisance (-> Saint-Denis);Pernety",
"Pernety (-> Saint-Denis);Gaite",
"Gaite (-> Saint-Denis);Montparnasse - Bienvenue",
"Montparnasse - Bienvenue (-> Saint-Denis);Duroc",
"Duroc (-> Saint-Denis);Saint-Francois-Xavier",
"Saint-Francois-Xavier (-> Saint-Denis);Varenne",
"Varenne (-> Saint-Denis);Invalides",
"Invalides (-> Saint-Denis);Champs Elysees - Clemenceau",
"Champs Elysees - Clemenceau (-> Saint-Denis);Miromesnil",
"Miromesnil (-> Saint-Denis);Saint-Lazare",
"Saint-Lazare (-> Saint-Denis);Liege",
"Liege (-> Saint-Denis);Place de Clichy",
"Place de Clichy (-> Saint-Denis);La Fourche",
"La Fourche (-> Saint-Denis);Guy Moquet",
"Guy Moquet (-> Saint-Denis);Porte de Saint-Ouen",
"Porte de Saint-Ouen (-> Saint-Denis);Garibaldi",
"Garibaldi (-> Saint-Denis);Mairie de Saint-Ouen",
"Mairie de Saint-Ouen (-> Saint-Denis);Carrefour Pleyel",
"Carrefour Pleyel (-> Saint-Denis);Saint-Denis - Porte de Paris",
"Saint-Denis - Porte de Paris (-> Saint-Denis);Basilique de Saint-Denis",
"Basilique de Saint-Denis (-> Saint-Denis);Saint-Denis - Universite",
"Asnieres Gennevilliers - Les Courtilles (-> La Fourche);Les Agnettes",
"Les Agnettes (-> La Fourche);Gabriel Peri",
"Gabriel Peri (-> La Fourche);Mairie de Clichy",
"Mairie de Clichy (-> La Fourche);Porte de Clichy",
"Porte de Clichy (-> La Fourche);Brochant",
"Brochant (-> La Fourche);La Fourche",
"La Fourche (-> Asnieres Gennevilliers);Brochant",
"Brochant (-> Asnieres Gennevilliers);Porte de Clichy",
"Porte de Clichy (-> Asnieres Gennevilliers);Mairie de Clichy",
"Mairie de Clichy (-> Asnieres Gennevilliers);Gabriel Peri",
"Gabriel Peri (-> Asnieres Gennevilliers);Les Agnettes",
"Les Agnettes (-> Asnieres Gennevilliers);Asnieres Gennevilliers - Les Courtilles",
"Mairie de Saint-Ouen (-> Olympiades);Saint-Ouen",
"Saint-Ouen (-> Olympiades);Porte de Clichy",
"Porte de Clichy (-> Olympiades);Pont Cardinet",
"Pont Cardinet (-> Olympiades);Saint-Lazare",
"Saint-Lazare (-> Olympiades);Madeleine",
"Madeleine (-> Olympiades);Pyramides",
"Pyramides (-> Olympiades);Chatelet",
"Chatelet (-> Olympiades);Gare de Lyon",
"Gare de Lyon (-> Olympiades);Bercy",
"Bercy (-> Olympiades);Cour Saint-Emilion",
"Cour Saint-Emilion (-> Olympiades);Bibliotheque Francois-Mitterand",
"Bibliotheque Francois-Mitterand (-> Olympiades);Olympiades",
"Olympiades (-> Mairie de Saint-Ouen);Bibliotheque Francois-Mitterand",
"Bibliotheque Francois-Mitterand (-> Mairie de Saint-Ouen);Cour Saint-Emilion",
"Cour Saint-Emilion (-> Mairie de Saint-Ouen);Bercy",
"Bercy (-> Mairie de Saint-Ouen);Gare de Lyon",
"Gare de Lyon (-> Mairie de Saint-Ouen);Chatelet",
"Chatelet (-> Mairie de Saint-Ouen);Pyramides",
"Pyramides (-> Mairie de Saint-Ouen);Madeleine",
"Madeleine (-> Mairie de Saint-Ouen);Saint-Lazare",
"Saint-Lazare (-> Mairie de Saint-Ouen);Pont Cardinet",
"Pont Cardinet (-> Mairie de Saint-Ouen);Porte de Clichy",
"Porte de Clichy (-> Mairie de Saint-Ouen);Saint-Ouen",
"Saint-Ouen (-> Mairie de Saint-Ouen);Mairie de Saint-Ouen"];

// Shuffle
data = data.sort((a, b) => 0.5 - Math.random())

function onlyUnique(value, index, array) {
    return array.indexOf(value) === index;
    }



//  Put available values in input box
const datalist = document.getElementById("list-stations");
data.map(x => x.split(";")[1]).filter(onlyUnique).sort().forEach(
    function(item){
        var option = document.createElement('option');
        option.value = item;
        datalist.appendChild(option);
    }
);



// What will happen when the game advances one step

function consumeQuestion(data){
    qnum ++;
    let qa = data[qnum];
    question.innerHTML = qa.split(";")[0].replace("->", "&#187;");
    correctAnswer = qa.split(";")[1];
};

function compareAnswer(ans, correctAnswer){
    return ans.toLowerCase().trim() === correctAnswer.toLowerCase().trim()
}


function advance(){
    var ans = inputBox.value;
        played ++;
        var msg = "Wrong !";
        // Check if answer was good or not
        if(compareAnswer(ans, correctAnswer)){
            score ++;
            msg = "Correct !";
            submitted.style.background = '#61e885';
            info.innerText = "";
        }
        else{
            submitted.style.background = '#ff4a4a';
            info.innerText = `Correct answer was: ${correctAnswer}`;
        };
        
        submitted.innerText = `${msg} (Score: ${score} / ${played})`;
        
        // Ready up for next question
        inputBox.value = "";
        consumeQuestion(data)
}

inputBox.addEventListener('keydown', (event) => {
    if (event.key === 'Enter') {
        advance();
    }
});

document.getElementById("btn-submit").addEventListener("click", (event) => {
    advance();
    inputBox.focus();
});


// Call it once at load up
consumeQuestion(data);
